# Generated by Django 5.0.8 on 2024-08-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='uen',
            options={'verbose_name': 'Departamento UEN', 'verbose_name_plural': 'Departamentos UEN'},
        ),
    ]
