# Generated by Django 5.0.8 on 2024-09-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_customuser_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='uen',
        ),
        migrations.AddField(
            model_name='customuser',
            name='uen',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='usuario.uen'),
        ),
    ]
