# Generated by Django 5.0.8 on 2024-09-10 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0003_customuser_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrocostos', to='usuario.area')),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrocostos', to='usuario.regional')),
                ('uen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centrocostos', to='usuario.uen')),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('regional', models.ForeignKey(default='default_value', on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='usuario.regional')),
                ('uen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='usuario.uen')),
            ],
        ),
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='uen.rubro')),
            ],
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to='uen.centrocostos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to=settings.AUTH_USER_MODEL)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='uen.rubro')),
                ('subrubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='uen.subrubro')),
            ],
        ),
    ]
