# Generated by Django 5.0.8 on 2024-10-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuestomes',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=15),
        ),
    ]
