# Generated by Django 5.0.8 on 2024-09-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0001_initial'),
        ('usuario', '0004_remove_customuser_uen_customuser_uen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubro',
            options={'verbose_name': 'Rubro', 'verbose_name_plural': 'Rubros'},
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuestomes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rubro',
            name='regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubros', to='usuario.regional'),
        ),
    ]
