# Generated by Django 5.0.8 on 2024-09-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0002_alter_rubro_options_presupuesto_presupuestomes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='cuenta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='meses',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuestomes',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='rubro',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='subrubro',
            field=models.IntegerField(),
        ),
    ]
