# Generated by Django 5.0.8 on 2024-10-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0003_remove_presupuesto_meses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='meses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='presupuestomes',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=15),
        ),
        migrations.DeleteModel(
            name='PresupuestoMes',
        ),
    ]
