# Generated by Django 5.0.8 on 2024-09-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0003_alter_presupuesto_cuenta_alter_presupuesto_meses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuestomes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
