# Generated by Django 5.0.8 on 2024-09-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0004_alter_presupuesto_presupuestomes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presupuesto',
            old_name='cuenta',
            new_name='item',
        ),
    ]
