# Generated by Django 5.0.8 on 2024-09-18 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0005_rename_cuenta_presupuesto_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='uen.centrocostos'),
        ),
    ]
