# Generated by Django 5.0.8 on 2024-09-18 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0006_presupuesto_cuenta'),
        ('usuario', '0004_remove_customuser_uen_customuser_uen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='uen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='usuario.uen'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuesto', to=settings.AUTH_USER_MODEL),
        ),
    ]
