# Generated by Django 5.0.8 on 2024-09-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0007_presupuesto_uen_alter_presupuesto_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='monthlyTotals',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='rubrosTotals',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='updatedRubros',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
