# Generated by Django 5.0.8 on 2024-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0008_alter_presupuestoactualizado_monthlytotals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='presupuestomes',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='presupuestomes',
            name='presupuestomes',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=20),
        ),
    ]
