# Generated by Django 5.0.8 on 2024-09-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uen', '0008_presupuesto_monthlytotals_presupuesto_rubrostotals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='monthlyTotals',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='rubrosTotals',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='updatedRubros',
            field=models.JSONField(null=True),
        ),
    ]
